name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Whether it's support for a new media format or a UI improvement, we'd love to hear it.

  - type: textarea
    id: feature
    attributes:
      label: What would you like?
      description: Describe the feature or improvement you'd like to see.
      placeholder: |
        I'd like the plugin to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Why?
      description: How would this improve your workflow?
      placeholder: |
        This would help me because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution (optional)
      description: Do you have a specific idea of how this should look or work?
      placeholder: |
        Maybe a button that does... or support for [format]...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (optional)
      description: Screenshots, mockups, or links to similar features in other apps.
    validations:
      required: false
